rethinkdb:
  image: rethinkdb
  ports:
    - "8080:8080"
    - "28015:28015"
    - "29015:29015"
  volumes_from:
    - dbData

# It is recommended to use a separate container for data volumes.
# This provides some benefits, for e.g., the db container can be upgraded without affecting the data
dbData:
  image: busybox
  volumes:
    - /data
  command: echo Data Volume for db